Updates Deducteam's repository with latest version
Deducteam/Agda2Dedukti pull request #3
Opened 2022-01-10 09:23 UTC by thiagofelicissimo

2022-01-13 11:50 UTC, fblanqui commented
@thiagofelicissimo Next time, please do not use master as a branch name for a PR.

2022-01-13 12:26 UTC, fblanqui commented on README.md
> +This translator is written as an Agda backend, and thus needs Agda to be present. To have the last Agda version tested with this package, from the project root run `git clone https://github.com/thiag
This fork of Agda should be on https://github.com/Deducteam/. Note that this is actually a fork of https://github.com/GuillaumeGen/agda which itself is a fork of https://github.com/agda/agda. It would be better to create in https://github.com/Deducteam/ a direct fork of https://github.com/agda/agda.

Edit: I have just done it: https://github.com/Deducteam/agda. It would be nice now to add the branch last-version-jesper-pr on it, and change its name to something more meaningful like to_dk.

2022-01-13 12:40 UTC, fblanqui commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
The sentences are not very clear as you speak of unification but there is no unification in dkcheck, and you speak of rule checking but what is the relation between unification and rule checking? and what is rule checking?
I guess that you in fact speak of subject reduction here, right?

Anyway, if not already done, could you please open an issue on Lambdapi to give an example where Lambdapi subject reduction algorithm fails?

2022-01-13 13:40 UTC, fblanqui commented
```
14:37 ~/src/Agda2Dedukti (thiago) stack build
Could not parse '/home/blanqui/src/Agda2Dedukti/stack.yaml':
Aeson exception:
Error in $.resolver: failed to parse field 'resolver': expected ResolverWith (), encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
14:37 ~/src/Agda2Dedukti (thiago) stack --version
1.9.3.1 x86_64
Compiled with:
- Cabal-2.4.0.1
- Glob-0.9.3
- HUnit-1.6.0.0
- QuickCheck-2.12.6.1
- StateVar-1.1.1.1
- aeson-1.4.2.0
- aeson-compat-0.3.9
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.8.2
- ansi-wl-pprint-0.6.8.2
- array-0.5.3.0
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.3
- async-2.2.2
- attoparsec-0.13.2.2
- attoparsec-iso8601-1.0.1.0
- auto-update-0.1.5
- base-4.12.0.0
- base-compat-0.10.5
- base-orphans-0.8.1
- base-prelude-1.3
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.2
- basement-0.0.10
- bifunctors-5.5.4
- binary-0.8.6.0
- bindings-uname-0.1
- bitarray-0.0.1.1
- blaze-builder-0.4.1.0
- blaze-html-0.9.1.1
- blaze-markup-0.8.2.2
- byteable-0.1.1
- bytestring-0.10.8.2
- call-stack-0.1.0
- case-insensitive-1.2.0.11
- cereal-0.5.8.1
- clock-0.7.2
- colour-2.3.5
- comonad-5.0.5
- conduit-1.3.1.1
- conduit-extra-1.3.3
- connection-0.2.8
- constraints-0.10.1
- containers-0.6.0.1
- contravariant-1.5.2
- cookie-0.4.4
- cryptohash-0.11.9
- cryptohash-sha256-0.11.101.0
- cryptonite-0.25
- cryptonite-conduit-0.2.2
- data-default-class-0.1.2.0
- deepseq-1.4.4.0
- digest-0.0.1.2
- directory-1.3.3.0
- distributive-0.6
- dlist-0.8.0.6
- easy-file-0.2.2
- echo-0.1.3
- ed25519-0.0.5.0
- either-5.0.1.1
- enclosed-exceptions-1.0.3
- erf-2.0.0.0
- exceptions-0.10.2
- extra-1.6.17
- fast-logger-2.4.16
- file-embed-0.0.11
- filelock-0.1.1.3
- filepath-1.4.2.1
- free-5.1.1
- fsnotify-0.3.0.1
- generic-deriving-1.12.4
- ghc-boot-th-8.6.5
- ghc-prim-0.5.3
- hackage-security-0.5.3.0
- hashable-1.2.7.0
- hinotify-0.4
- hourglass-0.2.12
- hpack-0.31.2
- hpc-0.6.0.3
- hspec-2.6.1
- hspec-core-2.6.1
- hspec-expectations-0.8.2
- hspec-smallcheck-0.5.2
- http-api-data-0.4
- http-client-0.5.14
- http-client-tls-0.3.5.3
- http-conduit-2.3.7.1
- http-types-0.12.3
- infer-license-0.2.0
- integer-gmp-1.0.2.0
- integer-logarithms-1.0.3
- libyaml-0.1.1.0
- lifted-async-0.10.0.4
- lifted-base-0.2.3.12
- logict-0.6.0.3
- megaparsec-7.0.5
- memory-0.14.18
- microlens-0.4.10
- microlens-th-0.4.2.3
- mime-types-0.1.0.9
- monad-control-1.0.2.3
- monad-logger-0.3.30
- monad-loops-0.4.3
- mono-traversable-1.0.11.0
- mtl-2.2.2
- mustache-2.3.0
- neat-interpolation-0.3.2.4
- network-2.8.0.1
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.14.3.0
- parsec-3.1.13.0
- parser-combinators-1.0.3
- path-0.6.1
- path-io-1.4.2
- path-pieces-0.2.1
- pem-0.2.4
- persistent-2.9.2
- persistent-sqlite-2.9.3
- persistent-template-2.5.4
- pretty-1.1.3.6
- primitive-0.6.4.0
- process-1.6.5.0
- profunctors-5.3
- project-template-0.2.0.1
- quickcheck-io-0.2.0
- random-1.1
- regex-applicative-0.3.3
- regex-applicative-text-0.1.0.1
- resource-pool-0.2.3.2
- resourcet-1.2.2
- retry-0.7.7.0
- rio-0.1.8.0
- rts-1.0
- safe-0.3.17
- scientific-0.3.6.2
- semigroupoids-5.3.2
- semigroups-0.18.5
- setenv-0.1.1.3
- shelly-1.8.1
- silently-1.2.5
- smallcheck-1.1.5
- socks-0.5.6
- split-0.2.3.3
- stm-2.5.0.0
- stm-chans-3.0.0.4
- store-0.5.1.1
- store-core-0.4.4
- streaming-commons-0.2.1.1
- syb-0.7.1
- system-fileio-0.3.16.4
- system-filepath-0.4.14
- tagged-0.8.6
- tar-0.5.1.0
- template-haskell-2.14.0.0
- temporary-1.3
- text-1.2.3.1
- text-metrics-0.3.0
- tf-random-0.5
- th-abstraction-0.2.11.0
- th-expand-syns-0.4.4.0
- th-lift-0.7.11
- th-lift-instances-0.1.12
- th-orphans-0.13.7
- th-reify-many-0.1.9
- th-utilities-0.2.3.0
- time-1.8.0.2
- time-locale-compat-0.1.1.5
- tls-1.4.1
- transformers-0.5.6.2
- transformers-base-0.4.5.2
- transformers-compat-0.6.5
- typed-process-0.2.5.0
- unicode-transforms-0.3.6
- unix-2.7.2.2
- unix-compat-0.5.1
- unix-time-0.4.7
- unliftio-0.2.11
- unliftio-core-0.1.2.0
- unordered-containers-0.2.10.0
- uuid-types-1.0.3
- vector-0.12.0.3
- vector-algorithms-0.8.0.1
- void-0.7.3
- x509-1.7.5
- x509-store-1.6.7
- x509-system-1.6.6
- x509-validation-1.6.11
- yaml-0.11.1.0
- zip-archive-0.4.1
- zlib-0.6.2

Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.
```

2022-01-13 13:53 UTC, fblanqui commented
Ok, I had a version of stack too old. You should add in README.md to use a version of stack >= 2.7.3 and do stack upgrade if not.

2022-01-13 14:22 UTC, fblanqui commented
@thiagofelicissimo Thanks to give me the right to push on your PR.

2022-01-13 14:26 UTC, thiagofelicissimo commented
> @thiagofelicissimo Thanks to give me the right to push on your PR. There is a number of small typos I could fix by myself in README.md.

I've just added some improvements to the readme myself, and if I've done it right now you should have the right to push into my fork now.

2022-01-13 14:51 UTC, fblanqui commented
```
15:48 ~/src/Agda2Dedukti (thiago) make test-dk-noEta
[...]
cd theory/dk/eta && rm -f *.dko ; dkcheck -e univ.dk && dkcheck -e Agda.dk
Parse error at (46,6): Unexpected token 'Union'.
make: *** [Makefile:21 : theory-objects] Erreur 1
```

2022-01-13 14:55 UTC, fblanqui commented
I just created https://github.com/Deducteam/agda/tree/to_dk.

2022-01-13 14:55 UTC, thiagofelicissimo commented
> ```
> 15:48 ~/src/Agda2Dedukti (thiago) make test-dk-noEta
> [...]
> cd theory/dk/eta && rm -f *.dko ; dkcheck -e univ.dk && dkcheck -e Agda.dk
> Parse error at (46,6): Unexpected token 'Union'.
> make: *** [Makefile:21 : theory-objects] Erreur 1
> ```

Are you using the Dedukti version indicated in the readme?

2022-01-13 14:56 UTC, fblanqui commented
Ah no, right... Doesn't your PR work with master branches of dkcheck and lambdapi?

2022-01-13 15:00 UTC, fblanqui commented
I see that there are errors with the master branch of dkcheck. Are you going to fix them?

2022-01-13 15:00 UTC, thiagofelicissimo commented
> Ah no, right... Doesn't your PR work with master branches of dkcheck and lambdapi?

It should work with the master branch of dedukti, but for lambdapi I still need to check if the recent syntax changes cause any problems

2022-01-14 10:42 UTC, fblanqui commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
It seems that, in fact, this is a mistake in your translation. See https://github.com/Deducteam/lambdapi/issues/813.

2022-01-14 11:02 UTC, fblanqui commented
Concerning the extra-dep on https://github.com/Deducteam/agda.git, could you use a branch name instead of a commit number?

2022-01-14 12:21 UTC, thiagofelicissimo commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
The first example I gave was a simplification of the second, which corresponds more to the files the translator produces, and which is not accepted by Lambdapi. Anyway, it is possible that changing the places where the terms are expanded can fix this, but currently the part related to eta is more or less as Guillaume left it. To be sincere I'm not that convinced by this method of annotating terms, I find it hackish and to me it is unclear whether it is always sound. I would be curious to see how much of the Agda library really needs eta.

2022-01-14 14:04 UTC, jespercockx commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
I remember discussing eta-equality with Guillaume and the different ways it could be encoded in Dedukti. 

First of all, we did investigate whether eta was actually required for the standard library and found out that without it you get into problems very quickly. The worst problem is not even eta for functions, but rather for pairs and for the unit type. In Agda code it is not very usual to pattern match on those since doing so is not necessary because of eta, so to make the code work *without* eta would require a lot more matching. I don't remember the exact number but I think it was less than 20% of the standard library that checks without eta because of this (perhaps Guillaume still has the precise number).

The second thing I remember is that encoding eta-equality in a complete way is actually really challenging. It's not enough to just eagerly eta-expand all terms of function or record type; you need to allow eta-expansion of neutral terms whose type might compute to a function or record type once the free variables are instantiated. The only way we figured to make this actually work in general is by essentially annotating each term that might be subject to eta-expansion with its type, and add rewrite rules to do the expansion "on the fly" once the type computes further.

Of course, this solution has rather horrible effects on the size of terms and efficiency  of conversion. But as far as I understand it's a fundamental price to pay for eta-equality if you don't have typed conversion. The alternative would be to add some form of eta-equality (or equivalently extensionality rules, as in Andromeda 2) to Dedukti. Is this still out of the question?

2022-01-14 14:24 UTC, fblanqui commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
Lambdapi has an "eta" flag (see https://lambdapi.readthedocs.io/en/latest/queries.html#flag) but for functions only, that could be used (it is used for translating Isabelle to Dedukti). But it would be nice if we can do translations without using it.

2022-01-14 15:18 UTC, jespercockx commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
Right, I agree it would be nice, it is just that I am a bit doubtful that there is any possible encoding that doesn't blow up terms to completely ridiculous sizes. But I might be wrong.

2022-01-14 16:06 UTC, thiagofelicissimo commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
Hi Jesper, thanks a lot for these informations. Indeed, only 20% is very bad. I had some options in mind concerning eta, and I guess that this throws out my first one, which would be to drop support for it (anyway, I would also like to check how other popular libraries do without eta, even though it is likely that we will have similar numbers).

What bothers me the most with the translation of eta is not the fact that the terms or huge, or that typechecking is slower, but the fact that it is not clear to me when we should expand a term or not, and whether this can be done in a sound and conservative way. In his thesis, Guillaume's shows soudness only for eta for functions, but to me it is unclear how this interacts with other features like pattern matching and what happens when we also add records. Moreover, the fact that variables are not anymore represent by variables, and the fact that eta annotated terms can have multiple representations (by adding as many etas before as we want) also bother me.

A second option I thought of would be to use rather eta-reduction: if we have for instance symbols abs and app, we could have the rule `abs A B (\x. app A B M[] x) --> M[]`, and for records we could have `pair A B (fst A B p) (snd A B p) --> p`. This brings two problems: 1) As these rules are not left-linear, we lose confluence on untyped terms, and I don't know would we would show them confluent for the type ones (maybe the work of Gaspard could help us?) 2) This does not deal with eta for the unit type, but as far as I know this is the only degenerate case 3) The reduction semantics of Agda wouldn't be preserved, but this does not matter for the type-checking (except for the unit type)

A third option might be to see if we can do transformations that allow to reduce the use of eta. Of course, this would not always work, but it could make us improve from 20% to something acceptable. One case which I've seen for instance is
```
record Box : Set where
  constructor cons
-- uncommenting the following line breaks the proof
--  no-eta-equality
  field openBox : Nat

b1 : Box
Box.openBox b1 = 3

b2 : Box
b2 = cons 3

p : b1 ≡ b2
p = refl
```
Here we need eta to have `b1 = cons (openBox b1) = cons 3` to then conclude. However, if we would be able to translate copatterns as constructors (for the inductive case of records) and thus translate `b1` by `cons 3`, then we wouldn't need eta here. Anyway, this is a bit specific of an example, and I would need some more real world examples to see how feasible this is.

Another option which I think is very little unlikely is if Deducteam accepts to add typed-rewriting into Dedukti. I would like to know what Frédéric and the others think about that, but I have the impression that the main problem here is that, because we use untyped rewriting, we are able to use all the work that already exists on it. I don't know much about this, but is there a general theory for "typed rewrite systems", like those of Agda and Coq? Is there a general way of showing confluence in these cases for instance? I sincerely don't know much about this, so I would like to know what others think.

2022-01-14 16:14 UTC, fblanqui commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
Concerning the first part, we could declare η as sequential (see Matching strategy modifier in https://lambdapi.readthedocs.io/en/latest/commands.html#symbol) and add the rule η _ $x --> $x.

Concerning non-left-linear rules, this does not matter as long as you have CR on typed terms. Proving it is another story.

Concerning the last part, I don't think that Coq uses typed rewriting but things may have changed.

2022-01-14 16:23 UTC, jespercockx commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
> the fact that it is not clear to me when we should expand a term or not

The conclusion we reached is that to comply fully with Agda's notion of conversion, you'd need to *always* expand terms if they are of a function or record type. Anything less causes possible disagreement between typed conversion and the untyped one.

> second option I thought of would be to use rather eta-reduction

Based on my experience with implementing Agda, doing eta-contraction is just asking for problems. See https://github.com/agda/agda/issues?q=label%3Aeta-contract for a list of issues we had/have related to eta-contraction. In particular, https://github.com/agda/agda/issues/2732 shows that eta-contraction is not even type-preserving. 

> A third option might be to see if we can do transformations that allow to reduce the use of eta.

I agree that this is an option, however I would first contact Guillaume about this since I know he already spent a lot of time trying to do this, and I would hate you wasting a lot of time repeating his failed attempts.

> Another option which I think is very little unlikely is if Deducteam accepts to add typed-rewriting into Dedukti.

You do not need typed rewriting, in fact Agda uses untyped reduction. However you do need to have typed *conversion*, which is a different beast. Do you know if the Deducteam thinks any differently about having typed conversion?

2022-01-14 16:27 UTC, jespercockx commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
I can recommend https://arxiv.org/abs/2103.07397 if you want to learn more about the general class of typed conversion algorithms used by languages like Agda (though I do not fully agree with their treatment of constructor parameters and other forced arguments.)

2022-01-14 18:27 UTC, fblanqui commented
Le 14/01/2022 à 17:24, Jesper Cockx a écrit :
> Do you know if the Deducteam thinks any differently about having typed 
> conversion?

We have no such project at the moment but we are open if it appears to 
be really necessary.

2022-01-14 19:51 UTC, thiagofelicissimo commented on README.md
> +Introducing a new feature into the translation should help to typecheck more files. However, in the case of Lambdapi, when introducing eta we see that the number of checked files decreases. This is b
Thanks Jesper for the reference, I'll take a look at it. 

I'll also ask Guillaume regarding the third option. 

About the view of Deducteam on typed conversion, I'm not sure what the others think about this. In what concerns myself, I still need to look more into it to know how it allows to mix untyped rewriting. 

Regarding agda/agda#2732, I've thought a bit about this example, and I still think that this does not rule out the option of eta reduction. Actually, I had already noticed before that eta-reduction rules, unlike the rules for the inductive type eliminators, cannot always have their parameters/indices linearized while still preserving typing. For instance, if we consider the dependent pair type, if we spell out all the implicit arguments and reduction rules we would have something like this
```
Σ : Π (A : Set) (B : A → Set), Set
in-Σ : Π (A : Set) (B : A → Set) (a : A) (b : B a), Σ A B
fst : Π (A : Set) (B : A → Set) (p : Σ A B), A
snd : Π (A : Set) (B : A → Set) (p : Σ A B), B (fst A B p)
fst _ _ (in-Σ _ _ $a _) ↪ $a
snd _ _ (in-Σ _ _ _ $b) ↪ $b
```
We still need to add the eta-reduction rule, but if we add 
```
in-Σ $A $B (fst $A' $B' $p) (snd $A'' $B'' $p) ↪ $p
```
then, by taking for instance `p = in-Σ Nat (λ _, eq Nat zero zero) zero (refl Nat zero)` we would have
```
in-Σ Nat (λ x, eq Nat zero x) (fst Nat (λ x, eq Nat zero zero) p) (snd Nat (λ x, eq Nat zero zero) p) 
↪  p
```
however the rhs has type `Σ Nat (λ _, eq Nat zero zero)`, whereas the lhs has type `Σ Nat (λ x, eq Nat zero x)`. Therefore, we should have taken the rule
```
in-Σ $A $B (fst $A $B $p) (snd $A $B $p) ↪ $p
```
which is indeed type-preserving, and cannot be applied to our previous example. If we spell out all the implict arguments in agda/agda#2732, it seems to me that the cause of the issue is that Agda apparently applies the version of the rule with linearized parameters, which indeed does not preserve typing. Here is an encoding in Lambdapi of this example with all the arguments explicited, and with the version with non-linear parameters.
```
// Encoding of the Agda fragment needed for this example
constant symbol L : TYPE;
constant symbol lzero : L;
constant symbol lsucc : L → L;

constant symbol U : L → TYPE;
symbol El : Π l : L, U l → TYPE;

// Encoding of A : Set
constant symbol A : U lzero;

// Encoding of record definition
constant symbol R : Π l : L, U l;
symbol Rf : Π l : L, El l (R l) → El lzero A;
symbol Rcons : Π l : L, El lzero A → El l (R l);
rule Rf $l (Rcons $l' $x) ↪ $x;
rule Rcons $l (Rf $l $x) ↪ $x;

// Encoding of 
//  a : Level
//  r : R a
//  C : ∀ b (r : R b) → Set
constant symbol a : L;
constant symbol r : El a (R a);
constant symbol C : Π (b : L), El b (R b) → U lzero;

// Encoding of 
//  test : C (lsuc a) record{ f = R.f r}
constant symbol test : El _ (C (lsucc a) (Rcons (lsucc a) (Rf a r)));

assert ⊢ Rcons (lsucc a) (Rf a r) ≡ r; // fails
```

Anyway, I'm still not completly sure that eta-reduction would not also cause some problems elsewhere. In particular, the biggest obstacle for this option in my opinion is proving confluence, without which we cannot have conservativity.

2022-01-14 19:53 UTC, thiagofelicissimo commented
> Concerning the extra-dep on https://github.com/Deducteam/agda.git, could you use a branch name instead of a commit number?

I didn't find this option in the Stack documentation, so I don't think this is possible

2022-01-17 10:22 UTC, fblanqui requested changes
This PR is almost ready to be merged. Just a few details to fix.

2022-01-17 10:22 UTC, fblanqui commented on src/Compiler.hs
> +        -- trought the covering checker
typo: trought -> through

2022-01-17 10:22 UTC, fblanqui commented on src/Compiler.hs
> +        reportSDoc "bla" 3 $ return $ text "ty Here" <+> pretty ty
What "bla" means?

2022-01-17 10:22 UTC, fblanqui commented on stack.yaml
> +    commit: b026db1fa2fbc4bafeff0d0a997d36ac07a94dc5
Could you put a branch name instead of a commit number?

2022-01-17 10:22 UTC, fblanqui commented on tests/files/coindMus.agda_
> +{-# OPTIONS --guardedness #-}
What is the meaning of the .agda_ file extenstion?

2022-01-18 09:54 UTC, thiagofelicissimo commented on stack.yaml
> +    commit: b026db1fa2fbc4bafeff0d0a997d36ac07a94dc5
like I previously said, this does not seem to be possible

2022-01-18 09:55 UTC, thiagofelicissimo commented on tests/files/coindMus.agda_
> +{-# OPTIONS --guardedness #-}
This is just a test file that was causing problems, so I changed its extension so it wouldn't be used in the tests. However, with the new test suite, this is no longer needed

2022-01-18 09:58 UTC, thiagofelicissimo commented on src/Compiler.hs
> +        reportSDoc "bla" 3 $ return $ text "ty Here" <+> pretty ty
This is a debugging key, I renamed it to toDk2

2022-01-18 09:58 UTC, thiagofelicissimo commented on src/Compiler.hs
> +        -- trought the covering checker
done

2022-01-18 19:55 UTC, fblanqui commented
@thiagofelicissimo Thanks to close the conversations that are solved. Do you have more modifications to do?

2022-01-18 19:57 UTC, thiagofelicissimo commented
> @thiagofelicissimo Thanks to close the conversations that are solved. Do you have more modifications to do?

No, if it's ok for you, you can merge it

2022-01-19 06:10 UTC, merged